---
title: "5AirbnbFinal"
author: "Jeanette Henry"
date: "December 11, 2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(xgboost)
library(readr)
library(stringr)
library(caret)
library(car)
library(DMwR)
library(Hmisc)
library(plyr)
library(dplyr)
library(tidyr)
library(data.table)
library(DescTools)
library(Matrix)
library(glmnet)
library(plotrix)
library(Ckmeans.1d.dp)

set.seed(0)
setwd("C:/Users/Jeane/MSDS/Proj2")
load("C:/Users/Jeane/MSDS/Proj2/trn_wrkspc.RData")
```


```{r cars}
folder='analysis1201'
summary(xgb)
```


```{r pressure, echo=FALSE}
plot(xgb$evaluation_log, 
     main="Training Evaluation Log (n=100)",
     ylab = "NDCG5 score", xlab="iteration",col='blue')
```

```{r cont}
importance_matrix = xgb.importance( model = xgb)

print(head(importance_matrix))

gp = xgb.ggplot.importance(head(importance_matrix, n=6))
print(gp) 



```

```{r}
#sample_submission_NDF <- readRDS("cache/sample_submission_NDF.RData")

#X_test_predictions <- readRDS(paste0("cache/",folder,"/test/X_test_predictions_part2_",i,".RData"))
predictions <- X_test_predictions[c('NDF','US','other','FR','CA','GB','ES','IT','PT','NL','DE','AU')]
predictions <- t(as.matrix(predictions))
rownames(predictions) <- c('NDF','US','other','FR','CA','GB','ES','IT','PT','NL','DE','AU')
predictions_top5 <- as.vector(apply(predictions, 2, function(x) names(sort(x)[12:8])))

# create submission 
X_test_submission_list <- list()
for (i in 1:nrow(X_test_id)) {
  X_test_idx <- as.character(X_test_id$id[i])
  X_test_ids <- rep(X_test_idx, 5)
  X_test_submission <- data.frame(id = X_test_ids,
                                  id_num = 1:5)
  X_test_submission_list[[i]] <- X_test_submission
}
X_test_submission <- bind_rows(X_test_submission_list)
X_test_submission$country <- predictions_top5

# create submission 
submission_list <- list()
for (i in 1:nrow(sample_submission_NDF)) {
  submission_idx <- as.character(sample_submission_NDF$id[i])
  submission_ids <- rep(submission_idx, 5)
  submission <- data.frame(id = submission_ids,
                           id_num = 1:5)
  submission_list[[i]] <- submission
}
submission <- bind_rows(submission_list)

submission <- dplyr::left_join(submission,
                               X_test_submission,
                               by = c("id", "id_num"))
submission$id_num <- NULL

# generate submission file
file_name <- "JrHsub"
write.csv(submission, paste0("cache/", folder, "/", file_name,".csv"), quote=FALSE, row.names = FALSE)


```

```{r}
X_test_predictions$country_destination <- NULL
X_test_predictions$id_num<-NULL
X_test_predictions$country_destination_num<-NULL
print(head(X_test_predictions))
print(head(submission, n=12))


```

```{r}
summary(X_test_predictions)

```

```{r}
